### ISSUE TITLE
Integrate Postmark into Dittofeed

### ISSUE THREAD

**Issue by pcr0wley** [crowleysystems/dittofeed#5]
Currently we just have basic SMTP integration for Postmark in Dittofeed. This means that we can't see any send statistics.

It would be helpful to have full Postmark integration.

@SergioPSV Can you check with Max and see how the bounty program works? We could put a bounty on this of $100 or $200.

**Comment by SergioPSV** [comment]
@pcr0wley Are we not using SendGrid in Dittofeed now?

**Comment by pcr0wley** [comment]
We are using SendGrid in Staging, however I was planning on using Postmark in Production.

We have full integration for Postmark in Odoo and historically they have worked well. Good discoverability and no issues with our campaigns.

**Comment by SergioPSV** [comment]
@pcr0wley Okay, I'll ask Max about it.

**Comment by SergioPSV** [comment]
@pcr0wley I suspect that they were already working on this, because 2 hours after they assigned the bounty they already created a pull request

Also Max put up the bounty instead of us
https://github.com/dittofeed/dittofeed/pull/642

**Comment by SergioPSV** [comment]
@pcr0wley Postmark support has already been added and is available in settings

<img width="1260" alt="image" src="https://github.com/crowleysystems/dittofeed/assets/32548311/7d4677f5-15fe-406d-9a9b-363afbd8e81c">

**Comment by pcr0wley** [comment]
I enabled Postmark processing in Production, per https://docs.dittofeed.com/integrations/channels/postmark.

The test failed with a `400` error, but that may be due to not having an email in Dittofeed to match.

@SergioPSV Can you setup hosted Dittofeed (Staging) with our dev Postmark server?

**Comment by SergioPSV** [comment]
@pcr0wley I configured postmark for staging, emails are sent successfully but tracking does not work, so Max is now fixing it
