### ISSUE TITLE
Users are not saved in the self-hosted version

### ISSUE THREAD

**Issue by SergioPSV** [crowleysystems/dittofeed#7]
In tab https://marketing.crowleymarine.com/dashboard/users must be saves all users which identity in events. Now I see that users are not saved, so emails cannot be sent. Max on slack suggested what needs to be checked and asked a few questions.

> users and their properties are computed asynchronously, so it may take ~2 minutes for them to show up.
If they don't show up after that period of time, it suggests that your worker is not running, or the compute properties workflow within the worker is not running.

> I'd want to know a bit more about how you're running the code.

> I remember that your team is using the lite version, I'd want to ask what version you're running.
I'd also suggest running the admin command `./admin.sh reset-compute-properties ` from inside your container.

@pcr0wley Can you check what Max wrote? If this doesn't help, then I'll try to run it locally

**Comment by pcr0wley** [comment]
I think this issue should be fixed. I opened a terminal for our Dittofeed container and ran that command.

<img width="972" alt="Screenshot 2024-02-26 at 12 18 13 PM" src="https://github.com/crowleysystems/dittofeed/assets/913268/8f859770-763d-47cd-b7fa-6182f4c49375">

_This actually happened once previously. https://dittofeed-community.slack.com/archives/C04KJS12G0J/p1702414375825729?thread_ts=1702310263.484909&cid=C04KJS12G0J_

**Comment by pcr0wley** [comment]
I did the following:
- Updated our code to the latest from Dittofeed
- Rebuilt Docker images
- Restarted Dittofeed
- Ran code to `reset-compute-properties`

@SergioPSV Can you see if that works?

You might be able to get a look at our Temporal UI. It is http://34.207.180.61:8080/. _If your IP is not whitelisted let me know what it is and I can add it._

If that doesn't work ask Max what we can look for to troubleshoot this.

**Comment by pcr0wley** [comment]
I just tried sending an event and identifying a user. Both seemed to have worked.

**Comment by SergioPSV** [comment]
@pcr0wley Yes, everything works great, about 300 users have already been added
