### ISSUE TITLE
Discuss paying for Dittofeed

### ISSUE THREAD

**Issue by pcr0wley** [crowleysystems/dittofeed#8]
I received the following message from Max (at Dittofeed):

> Hi Paul, we've had a great time working closely with your team in our slack channel, building dedicated features and providing support. We'd definitely like to continue the relationship.
> 
> We do ask teams who we're providing dedicated support to for a $300/mo support fee. It'd go a long way towards ensuring that our team is capable of sustainably developing Dittofeed, for the long-haul.

@SergioPSV What do you think? Is Dittofeed stable enough to keep using? Should we pay for support?

**Comment by SergioPSV** [comment]
We already send almost all emails to the sandbox, I check the data is correct

https://account.postmarkapp.com/servers/12758882/streams/outbound/events

**Comment by pcr0wley** [comment]
> @pcr0wley I think that without support we will not be able to use Dittofeed, since all the messages to support were related to the fact that Dittofeed did not work as expected (here I do not take into account that they added postmark support specifically for us)
> My opinion is that this fee is quite high, since they have not yet had a release and a lot of functionality is missing, but if they add the functions we need (for example, an SDK with which we can send a popup to our website), then it will be justified.
> 
> - Will we be able to use dittofeed without paying for support?

Probably not at this point.

> - What benefits will be provided to us if we pay for support?

I imagine quicker bug fixes and the ability to help guide the future direction of the software.

> - How much did we pay for using Customer.io? and was there any paid support?

Customer.io was over $1,000 per month. There was support, however we rarely had issues.

**Comment by SergioPSV** [comment]
> Customer.io was over $1,000 per month. There was support, however we rarely had issues

I think it makes sense to pay for support so that they add all the necessary functions that we need, we will just start using Dittofeed as the main tool

**Comment by pcr0wley** [comment]
I responded to Max and asked him about multi-tenancy. He responded with this:

> Just had a talk with my co-founder. Easy support for multi-tenancy is one of the key features we plan to keep closed-source. Our options are,
> 1. Continue to use cloud hosted dittofeed with support for multi-tenancy.
> 2. Use a licensed self-hosted version of dittofeed with easier support for multi-tenancy, including bundled oauth support and workspace admin API's.
> 3. Continue to use the open-source version of Dittofeed, which is single-tenant by default.
> Options 1., and 2. entitle your team to dedicated support via a Slack Connect channel, and prioritized feature development. You can also opt into this support with option 3. for a fee.
> We've really enjoyed working with you and your team. Let me know what works best for you!

Basically they would offer us a separately licensed version, however unlike opensource once we stopped paying the license fee we would lose the advanced features.

I say we keep using opensource without paying the support fee. We can still ask them to fix bugs and other issues.

**Comment by pcr0wley** [comment]
Dittofeed at its core is setup for multi-tenancy. Once we require that (in the future) we would just need to fork the repo and add a couple of API endpoints.

I keep comparing it with Customer.io as it is the gold standard, but always run into the same two things:
1. Customer.io is too expensive for broadcast emails. They charge by user. We would pay $100/month for transactional emails and over $1,000/month if we wanted to use it for Broadcasts.
2. No white-labeling. Although future customers would probably not need to create their own Journeys, they would still want to customize their email layouts. Not possible with Customer.io.

**Comment by pcr0wley** [comment]
> I say we keep using opensource without paying the support fee. We can still ask them to fix bugs and other issues.

Following up on this I changed my stance a bit. We _should_ pay the support fee for the next 6 months. That will guarantee priority support during our busy season, at a time when Dittofeed still has some issues. Also we will be able to request all of our custom features during this time.

**Comment by SergioPSV** [comment]
Makes sense. But I think that Dittofeed will fix all the problems much faster and even within 4 months all the necessary functions will work.
I also agree with you that it is better to receive support for 6 months until our busy season ends

**Comment by pcr0wley** [comment]
Done. We now have a paid monthly support and consulting subscription with Dittofeed.
