### ISSUE TITLE
High memory usage in ClickHouse

### ISSUE THREAD

**Issue by pcr0wley** [crowleysystems/dittofeed#9]
Dittofeed is causing our ClickHouse instance to have high memory usage and in the case of today bringing down the database.

It seems that this issue is caused by specific queries that calculate computed properties.

![screenshot_2024-03-15_at_2 07 45_pm](https://github.com/crowleysystems/dittofeed/assets/913268/f5b56f21-b2a0-4e4e-99d4-835829501c86)

**Comment by pcr0wley** [comment]
Currently we are on `clickhouse.cloud` Development service for ~$159/month.
- 2x 8GB 1vCPU

The recommended that we move up to Production. Minimum pricing would be $505/month.
- 3x 8GB 2vCPU

The next step up is $1,009/month.
- 3x 16GB 4vCPU

In any case the replication only helps with READs on replicated tables. Plausible tables are not replicated and support will not be added (https://github.com/plausible/analytics/issues/3751#issuecomment-1953817351). _I believe that Dittofeed tables are created as Replicated._

Although fault tolerance would be nice, it isn't something we need. Especially with ClickHouse.

As such we should explore other options that have better pricing.

The first I cam across was `double.cloud`. They have some of the original ClickHouse engineers, and also have hosted Kafka which we will eventually need. The service below is only a single instance, however it will give us better performance and is ~$250/month.
- 1x 16GB 4vCPU

**Comment by pcr0wley** [comment]
The issue is most likely due to Dittofeed (they themselves only run on a 6GB RAM server), however it would still be good to upsize our instance and prepare for the future. As such we'll probably move off of ClickHouse Cloud.

I opened https://github.com/crowleysystems/odoo/issues/1460 to explore DoubleCloud.

In the meantime Dittofeed is disabled. As far as I know this shouldn't affect anything since we aren't using it in Production yet.

**Comment by pcr0wley** [comment]
> In the meantime Dittofeed is disabled. As far as I know this shouldn't affect anything since we aren't using it in Production yet. Also I disabled all of the Dittofeed Automated Actions.

@SergioPSV I migrated to a new database (https://github.com/crowleysystems/dittofeed/issues/10) and everything seems to be working. Please check it on your end.

Also I reenabled all Automated Actions.

**Comment by SergioPSV** [comment]
@pcr0wley Having looked at the sent emails and everything is working properly

**Comment by pcr0wley** [comment]
Aside from migrating to the new database I also updated Dittofeed.

@SergioPSV Let's check things out for one more day. As long as everything is still good tomorrow we can completely switch over to Dittofeed.

**Update process**
```
docker-compose down
git pull
docker-compose -f docker-compose.pilot.yaml build
docker-compose -f docker-compose.pilot.yaml run dittofeed ./admin.sh prisma migrate deploy
docker-compose -f docker-compose.pilot.yaml up -d
```

**Comment by SergioPSV** [comment]
@pcr0wley Sounds good. If something goes wrong, we can use this guide to update https://docs.dittofeed.com/deployment/self-hosted/upgrade-guide/v0-11-0
